### ISSUE TITLE
Support "mostRelevantPost" preview

### ISSUE THREAD

**Issue by zgq354** [ganuonglachanh/flarum-sonic#1]
Hello, I am looking for a better flarum search extension for my forum, just test sonic and felt good.

But I found that the return data missed the "mostRelevantPost" fields.
![image](https://user-images.githubusercontent.com/9024954/131760116-5e95eb9c-b9bf-43f5-a5f7-57f64a35ad7c.png)
![image](https://user-images.githubusercontent.com/9024954/131763307-0091a341-fad4-4f8d-8ad4-45c560d1d691.png)

expected:
![image](https://user-images.githubusercontent.com/9024954/131760206-a4ca3d8f-785b-48cd-b769-9cd7bfa78590.png)
![image](https://user-images.githubusercontent.com/9024954/131762082-bba7190c-b95f-4bbd-8e3f-2d484dd499f1.png)

Maybe we need to implements this without "match aganist" SQL query.

reference: https://github.com/0xffff-one/0xffff-flarum/issues/20#issuecomment-910942587

**Comment by ganuonglachanh** [comment]
Hi, thanks for your report, please try the new release :+1:
