### ISSUE TITLE
请问支持内容搜索吗，我装了之后只能搜索标题，是这样的吗

### ISSUE THREAD

**Issue by aholeye** [ganuonglachanh/flarum-sonic#5]

**Comment by aholeye** [comment]
要新的数据才会有内容搜索

**Comment by n0099** [comment]
the docs said that u should run `php flarum sonic:addtoindex` after install: https://github.com/ganuonglachanh/flarum-sonic/blob/ebbeb19331055f7491157018ea4b5c7a09fc373d/README.md?plain=1#L14
